### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [plasma-umass/Hound#1]
I would like to point out that identifiers like "[`__AO_CHUNK_H__`](https://github.com/plasma-umass/Hound/blob/ba8b04b7c1e444bfcaf03dc48aeb12be1400a3af/AOChunk.hpp#L1)" and "[`__TRAP_HANDLER_H__`](https://github.com/plasma-umass/Hound/blob/ba8b04b7c1e444bfcaf03dc48aeb12be1400a3af/traphandler.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by emeryberger** [comment]
Done.

**Comment by elfring** [comment]
I suggest to [reconsider the use of double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797) at more source code places.

**Comment by emeryberger** [comment]
I think I have now chased these all down.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/plasma-umass/Hound/commit/ec3daf1123f59a8573a15ef1d6d53896c310e19d#diff-98ba56d25d28991fe5fb1f3fe240d0e1R1) left over?
